services:
  dev_maksim:
    build:
      context: .
      dockerfile: docker/dev_maksim.Dockerfile
    container_name: dev_maksim
    tty: true
    volumes:
      - .:/home/$USER/app
    ports:
      - "3000:3000"
      - "5173:5173"

  dev_fabi:
    build:
      context: .
      dockerfile: docker/dev_fabi.Dockerfile
    container_name: dev_fabi
    tty: true
    volumes:
      - .:/home/$USER/app
      - .config/nvim:/home/$USER/.config/nvim
    environment:
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
    ports:
      - "3000:3000"
      - "5173:5173"

