services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules:/app/vite-project/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
      - "5173:5173"
    stdin_open: true
    tty: true
    command: sh

volumes:
  node_modules:
    driver: local
