services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules_FE:/app/core/frontend/node_modules
      - node_modules_BE:/app/core/backend/node_modules
      - node_modules_core:/app/core/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    stdin_open: true
    tty: true
    command: sh


  dev_maksim:
    build:
      context: .
      dockerfile: docker/dev_maksim.Dockerfile
    container_name: dev_maksim
    tty: true
    volumes:
      - .:/home/$USER/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"

  dev_fabi:
    build:
      context: .
      dockerfile: docker/dev_fabi.Dockerfile
    container_name: dev_fabi
    tty: true
    volumes:
      - .:/home/$USER/app
      - .config/nvim:/home/$USER/.config/nvim
    environment:
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
    ports:
      - "3000:3000"
      - "5173:5173"

volumes:
  node_modules_FE:
  node_modules_BE:
  node_modules_core:
