FROM node:22-alpine

WORKDIR /app

# COPY . .

# RUN cd core && npm i
# RUN cd core/frontend && npm i
# RUN cd core/backend && npm i

RUN apk update && apk add bash \
	--no-cache make

RUN echo 'alias dev="npm run dev"' >> /etc/bash/bashrc

ENTRYPOINT [ "./init.sh" ]

