
PYTHON=./py_env/bin/python
PIP=./py_env/bin/pip

env:
	python3 -m venv py_env
	$(PIP) install -r requirements.txt

#python3 -m pip install --user virtualenv
env_school_linux:
	python3 -m virtualenv py_env
	$(PIP) install -r requirements.txt
